# Generated by Django 3.2.7 on 2021-09-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='head0',
            new_name='description',
        ),
    ]
